schema_version: 1

context:
  name: mini-racer
  version: "0.13.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/bpcreech/PyMiniRacer/archive/refs/tags/v${{ version }}.tar.gz
  sha256: d80948ddf1c6d2ffdb8e9e3d698ced2c9f3277484975582c0434e6fa913817cb

build:
  number: 0
  script:
    - just build-dll
    - ${{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation
  dynamic_linking:
    binary_relocation: ${{ false if osx else true }}



requirements:
  build:
    - python <3.12 #See GoogleCloudPlatform/gcs-oauth2-boto-plugin#75 and GoogleCloudPlatform/gsutil#1888
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler("cxx") }}
    - if: not win
      then: pkg-config
    - six
    - gsutil
    - just
    - uv
    - wheel
    - httplib2 =0.22.0
    - setuptools >=80.9.0
    - types-setuptools >=80.9.0
    - babel
    - rust
  host:
    - python
    - pip
    - httplib2 =0.22.0
    - packaging >=25.0 
    - six
    - setuptools >=80.9.0
    - types-setuptools >=80.9.0
    - wheel
  run:
    - python

tests:
  - python:
      imports:
        - py_mini_racer
      pip_check: true

about:
  summary: Minimal, modern embedded V8 for Python.
  license: ISC
  license_file:
    - LICENSE
    - library_licenses/
  homepage: https://github.com/bpcreech/PyMiniRacer
  repository: https://github.com/bpcreech/PyMiniRacer

extra:
  recipe-maintainers:
    - HeavyTony2
