schema_version: 1

context:
  name: mini-racer
  version: "0.13.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/bpcreech/PyMiniRacer/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 569449c0a34028761b71c4cab0103e9628bb75f5d4a1e1ffcfd1416ca09e83f1

build:
  number: 0
  script: 
    - if: osx
      then: uv add clang==19.1.7
    - ${{ PYTHON }} builder/v8_build.py 
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  dynamic_linking:
    binary_relocation: ${{ false if osx else true }}



requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler("cxx") }}
    - if: not win
      then: pkg-config
    - six
  host:
    - python
    - setuptools >=80.9
    - mkdocs >=1.6.1
    - pip
    - httplib2 ==0.22.0
    - packaging
    - six
    - wheel
    - mdformat >=1.0.0
    - mypy >=1.19.0
    - ruff >=0.14.8
  run:
    - python

tests:
  - python:
      imports:
        - py_mini_racer
      pip_check: true

about:
  summary: Minimal, modern embedded V8 for Python.
  license: ISC
  license_file:
    - LICENSE
    - library_licenses/
  homepage: https://github.com/bpcreech/PyMiniRacer
  repository: https://github.com/bpcreech/PyMiniRacer

extra:
  recipe-maintainers:
    - HeavyTony2
