schema_version: 1

context:
  name: mini-racer
  version: "0.13.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/mini_racer-${{ version }}.tar.gz
  sha256: b93b28d74008f4ce084292a9c3b2057283ceaa3057c1aef71cb3f86874c0c6d7

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  dynamic_linking:
    binary_relocation: ${{ false if osx else true }}



requirements:
  build:
    - python <3.12 #See GoogleCloudPlatform/gcs-oauth2-boto-plugin#75 and GoogleCloudPlatform/gsutil#1888
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler("cxx") }}
    - if: not win
      then: pkg-config
    - six
    - gsutil
  host:
    - python
    - hatchling
    - hatch-fancy-pypi-readme
    - hatch-mkdocs
    - pip
    - httplib2 <0.30.0  #Apparent issues with httplib2 and gstuil
    - packaging
    - six
  run:
    - python

tests:
  - python:
      imports:
        - py_mini_racer
      pip_check: true

about:
  summary: Minimal, modern embedded V8 for Python.
  license: ISC
  license_file:
    - LICENSE
    - library_licenses/
  homepage: https://github.com/bpcreech/PyMiniRacer
  repository: https://github.com/bpcreech/PyMiniRacer

extra:
  recipe-maintainers:
    - HeavyTony2
