conda_build_tool: rattler-build
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
provider:
  linux_aarch64: default
  linux_ppc64le: default
test: native_and_emulated
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
conda_install_tool: pixi
azure:
  free_disk_space: true
  max_parallel: 35
noarch_platforms:
  - linux_64
  - win_64
  - linux_ppc64le
  - linux_aarch64
  